Test controllers
assadounto/Blog pull request #5
Opened 2022-09-23 09:40 UTC by assadounto

In this feature I tested controllers

2022-09-23 10:25 UTC, dasileker requested changes
### **Hi @assadounto,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**

- Linters are ✅.
- Commit messages are consistent 👌.

## Required Changes ♻️
_Check the comments under the review._

- **Hello and excellent work on adding the tests but there are some falling tests that need to be corrected. also the readme file is missing instructions on how to copy the repo and the necessary steps needed to run the app and run the tests,**

![Capture d’écran 2022-09-23 111828](https://user-images.githubusercontent.com/61562626/191941101-eb90eb5b-b1bc-4ce8-8b3a-6e653b462e4f.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 21:04 UTC, medaminedev66 requested changes
Hi @assadounto 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Your PR has no linters errors.

 ## Required Changes ♻️
- [ ] As mentioned by the previous reviewer,  your readme file is missing instructions on how to copy the repo and the necessary steps needed to run the app and run the tests. Please add some instructions to your Readme on how users can test your app 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 21:04 UTC, medaminedev66 commented on spec/requests/users_spec.rb
> +end
- [ ] Following the project requirements, the `show` action for the User controller should be tested.

2022-09-24 21:04 UTC, medaminedev66 commented on spec/requests/posts_spec.rb
> +end
- [ ] Following the project requirements, `index` and `show` actions for  Post controllers should be tested. I noticed that you have tested the index action for the User controller instead of the index action for the Post controller.

2022-09-24 23:04 UTC, Whoistolu commented on spec/requests/users_spec.rb
> +end
- [ ] [REQUIRED] Kindly check the implemented test as they are not passing. Please fix them and ask for another submission.
![Screenshot from 2022-09-24 23-58-51](https://user-images.githubusercontent.com/58692590/192121610-238aa4ca-40de-43ca-9fae-4e13e7c3a12f.png)

2022-09-24 23:08 UTC, Whoistolu requested changes
Hi @assadounto 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 11:59 UTC, prolajumokeoni approved these changes
Hi @assadounto, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 14:14 UTC, merged