Views
assadounto/Blog pull request #6
Opened 2022-09-23 21:21 UTC by assadounto

In this feature, I added views

2022-09-23 21:30 UTC, rloterh reviewed
Hi Rich,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted a project, whereby Stylelint linter checks are not showing. Kindly ensure that github actions are properly configured and that **all** required linters are showing and that checks are passing Kindly request for another code review when this fix is done.

 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-23 21:58 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @assadounto  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Highlights 💯
✔️ Your git-flow is correct. 
✔️ You set up linter files and no errors. 
✔️ Your pull request is very professional. It has a meaningful title and summary. Keep it up.
___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [ ] Everything is working well. Kindly follow the wireframe. You can skip the style if you want.

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
@assadounto 
-  [ ] Kindly add more detail to the pull request description. 
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 

- Your commit messages should always start with capital letters and they should be an imperative tense. I see some of them are not like that. Instead of writing `Added style or Created the file` kindly write `Add style or Create the file`
- ***I write it as optional. But this is a [general requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=The%20commit%20message%20should%20be%20written%20in%20the%20imperative%20tense%20and%20capitalized) for every project. So you should pay attention to this in your next projects.***
- Kindly change them by using `git-rebase`. If you want to know how to change ı leave a few resources.
- [Video - How to change commit messages](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6)
- [Article - How to create good commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-09-23 21:58 UTC, ahmetbozaci commented on app/views/users/_user.html.erb
> +</div>
- [ ] Kindly make sure users' page match the wireframe

![image](https://user-images.githubusercontent.com/38635158/192061505-87d33907-6057-44fd-bf38-b401780e583f.png)

![image](https://user-images.githubusercontent.com/38635158/192061519-1d42906a-a43b-43d1-9109-03a94b1fd67d.png)

2022-09-23 21:58 UTC, ahmetbozaci commented on app/views/users/show.html.erb
> + <%=link_to 'see all posts' ,user_posts_path(@user)%>
- [ ] Kindly make sure user show page match the wireframe. 
- [ ] Kindly do not forget to put the see all posts button.

![image](https://user-images.githubusercontent.com/38635158/192061580-abfeab6a-b1da-4aeb-9542-379d2d7e727b.png)

![image](https://user-images.githubusercontent.com/38635158/192061596-ba70b048-88d3-47e4-8854-4d7506b6aab6.png)

2022-09-23 21:58 UTC, ahmetbozaci commented on app/views/users/_user.html.erb
> +           <div> <%= pluralize(user.postCounter, 'Post') %></div>
- [ ] The post counter method is not working you can see on the page it is still showing zero. Kindly fix it. OPTIONAL

![image](https://user-images.githubusercontent.com/38635158/192061773-74fe9833-352e-437b-9266-c6247ea8045b.png)

2022-09-23 21:58 UTC, ahmetbozaci commented on app/views/posts/_post.html.erb
> +
- [ ] Kindly make sure post index page match the wireframe
![image](https://user-images.githubusercontent.com/38635158/192061973-7c4f8b30-0e0e-4530-89f4-7f2738b085ee.png)
![image](https://user-images.githubusercontent.com/38635158/192061980-cd79c54e-078d-4ce7-aeb2-b81b73274331.png)

2022-09-24 15:36 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @assadounto, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean/Organized code
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 20:07 UTC, merged